[package]
name = "webhook-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.10.2"
dotenv = "0.15.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.1", features = ["process", "macros", "rt-multi-thread"] }
